In [2]:
import numpy as num
a = num.array([1, 2, 3, 4, 5])

print(a)

[1 2 3 4 5]


In [4]:
b= num.array([[1,2,3], [4,5,6]])
print (b.shape)

(2, 3)


In [5]:
b= num.array([[1,2,3], [4,5,6]])
print (b.reshape(3, 2))

[[1 2]
 [3 4]
 [5 6]]


In [9]:
c = num.array([[1,2,3],[4,5,6]])
c.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
a=num.arange(2,4)
print (a)

[2 3]
